market:
  exchange: NSE

universe:
  - RELIANCE.NS
  - TCS.NS
  - HDFCBANK.NS
  - INFY.NS
  - ICICIBANK.NS

historical_data:
  period: 5y
  interval: 1d

live_data:
  period: 5d
  interval: 1h

engine:
  update_interval_minutes: 5